name: rchain-ci
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  repository_dispatch:
    types: [bench-ci]
jobs:
  run-bench-ci:
    runs-on: ubuntu-latest
    container: rchain/buildenv
    steps:
      - name: Pull from repo
        uses: actions/checkout@v2
        with:
          repository: rchain/rchain
          ref: dev
          path: ./rchain

      - name: Set rchain repo commit hash
        working-directory: ./rchain
        run: echo "RCHAIN_SHA=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Test env
        run: echo $RCHAIN_SHA

      - name: Compile
        working-directory: ./rchain
        run: |
          export SBT_OPTS="$SBT_OPTS -Dsbt.task.timings=true -Xmx2500m -Xss2m"
          sbt update compile

      - name: Run bench
        working-directory: ./rchain
        run: |
          sbt "rspaceBench/jmh:run -rff /$RCHAIN_SHA-report.json -rf json"

      - name: Pull ci repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.RBOT_TOKEN }}
          path: ./rchain-ci

      - name: Move file
        working-directory: ./rchain-ci
        run: |
          mv /$RCHAIN_SHA-report.json ./report/

      - name: Commit report
        uses: EndBug/add-and-commit@v7
        with: 
          add: ${{format('report/{0}-report.json', env.RCHAIN_SHA)}}
          message: ${{format('{0} bench report', env.RCHAIN_SHA)}}
          committer_email: rbot-ci@rchain.coop
          author_name: rbot-ci
          committer_name: rbot-ci
          push: true
          cwd: ./rchain-ci
