name: rchain-ci
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  repository_dispatch:
    types: [bench-ci]
jobs:
  run-bench-ci:
    runs-on: ubuntu-latest
    container: rchain/buildenv
    steps:
      - name: Pull from repo
        uses: actions/checkout@v2
        with:
          repository: rchain/rchain
      - name: Compile
        run: |
          export SBT_OPTS="$SBT_OPTS -Dsbt.task.timings=true -Xmx2500m -Xss2m"
          sbt update compile

      - name: Run bench
        run: |
          sbt "rspaceBench/jmh:run -rff /report.json -rf json"

      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: /report.json

