name: rchain-ci
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  repository_dispatch:
    types: [bench-ci]
jobs:
  run-bench-ci:
    runs-on: ubuntu-latest
    container: rchain/buildenv
    steps:
      - name: Pull from repo
        uses: actions/checkout@v2
        with:
          repository: zsluedem/rchain
          ref: bench-test

      - name: Set rchain repo commit hash
        run: echo "RCHAIN_SHA=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Compile
        run: |
          export SBT_OPTS="$SBT_OPTS -Dsbt.task.timings=true -Xmx2500m -Xss2m"
          sbt update compile

      - name: Run bench
        run: |
          sbt "bench/jmh:run -rff /$RCHAIN_SHA-report.json -rf json"

      - name: Pull ci repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.RBOT_TOKEN }}

      - name: Move file
        run: |
          mv /$RCHAIN_SHA-report.json ./report/
      
      - name: Commit report
        uses: EndBug/add-and-commit@v7
        with: 
          add: ./report/$RCHAIN_SHA-report.json
          message: '$RCHAIN_SHA bench report'
          push: true

      - name: Upload report
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.RBOT_TOKEN }}
          gist_id: $GITHUB_SHA
          gist_file_name: report.json
          file_path: report.json
